# Data acquisition

Our goal in this session is to: 


1.   look at different ways to acquire Purple air data
2.   download Purple air data using an API

Let's start by importing all necessary packages for this session

In [2]:
!pip install purpleair

import pandas as pd
from purpleair.sensor import Sensor
from purpleair.network import SensorList

Requirement already satisfied: purpleair in /usr/local/lib/python3.7/dist-packages (1.2.5)
Requirement already satisfied: geopy in /usr/local/lib/python3.7/dist-packages (from purpleair) (1.17.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from purpleair) (1.3.5)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from purpleair) (2.23.0)
Requirement already satisfied: thingspeak in /usr/local/lib/python3.7/dist-packages (from purpleair) (1.0.0)
Requirement already satisfied: requests-cache in /usr/local/lib/python3.7/dist-packages (from purpleair) (0.9.2)
Requirement already satisfied: geographiclib<2,>=1.49 in /usr/local/lib/python3.7/dist-packages (from geopy->purpleair) (1.52)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->purpleair) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->purpleair) (2018.9)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas->purpleair) (1.21.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->purpleair) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->purpleair) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->purpleair) (2021.10.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->purpleair) (1.25.11)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->purpleair) (3.0.4)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in /usr/local/lib/python3.7/dist-packages (from requests-cache->purpleair) (1.4.4)
Requirement already satisfied: url-normalize<2.0,>=1.4 in /usr/local/lib/python3.7/dist-packages (from requests-cache->purpleair) (1.4.3)
Requirement already satisfied: cattrs<2.0,>=1.8 in /usr/local/lib/python3.7/dist-packages (from requests-cache->purpleair) (1.10.0)
Requirement already satisfied: attrs<22.0,>=21.2 in /usr/local/lib/python3.7/dist-packages (from requests-cache->purpleair) (21.4.0)
Requirement already satisfied: typing_extensions in /usr/local/lib/python3.7/dist-packages (from cattrs<2.0,>=1.8->requests-cache->purpleair) (3.10.0.2)
Requirement already satisfied: docopt<0.7.0,>=0.6.2 in /usr/local/lib/python3.7/dist-packages (from thingspeak->purpleair) (0.6.2)

How many Purpleair sensors are there in the world?

In [30]:
p = SensorList()  # Initialized 22,453 sensors!
p.to_dataframe(sensor_filter='outside',channel='parent')  #channel = parent or child, sensor_filter = 'outside', 'useful', 'family', and  'all'
#you can save this to a variable for further analysis
kk = p.to_dataframe(sensor_filter='outside',channel='parent') 
kk.to_excel('purpleair_sensors.xlsx')
kk

Child 566 lists parent 565, but parent does not exist!
Child 2861 lists parent 2860, but parent does not exist!
Initialized 22,453 sensors!

      parent        lat         lon  ... 6hour_avg 1day_avg  1week_avg
id                                   ...
14633   None  37.275561 -121.964134  ...      8.64     5.82       8.14
25999   None  30.053808  -95.494643  ...     19.85    15.55      14.14
14091   None  37.883620 -122.070087  ...     14.72     9.96      12.10
49409   None  18.759182   99.017172  ...     23.71    28.59      32.91
42073   None  47.185173 -122.176855  ...      4.02     8.95      11.58
...      ...        ...         ...  ...       ...      ...        ...
65005   None  36.783216  127.165218  ...     26.15    38.54      47.99
64995   None  36.691324  126.585255  ...     24.20    32.34      37.44
64093   None  36.710720  126.548390  ...     24.01    33.71      39.57
29747   None  36.761236  127.395300  ...     21.18    31.06      38.89
98309   None  36.718003  126.926841  ...     24.92    36.71      44.07

[16539 rows x 43 columns]

How is the air pollution levels in Hazelwood Canary?

In [80]:
se = Sensor(14633)
df = se.parent.get_historical(2,thingspeak_field='primary')
df

entry_id
996976     7.84
996977     7.53
996978     7.43
996979     7.70
996980     7.65
          ...
991942     9.88
991943    10.59
991944    10.58
991945    11.79
991946    12.05
Name: PM2.5 (CF=1) ug/m3, Length: 15024, dtype: float64

Let's look at the sensors in West Africa

In [47]:
kk_africa = kk[kk['lat']>3]
kk_africa = kk_africa[kk_africa['lat']<15]
kk_africa = kk_africa[kk_africa['lon']>3]
kk_africa = kk_africa[kk_africa['lon']<15]
kk_africa

hd = kk[(kk['lat'] > 3) & (kk['lon'] >3) & (kk['lat'] < 15)  & (kk['lon'] <15)]
hd

       parent        lat       lon  ... 6hour_avg 1day_avg  1week_avg
id                                  ...
118057   None   6.739415  6.083324  ...     57.45    44.01      18.85
57207    None   7.759338  4.603460  ...     43.92    46.17      63.30
116271   None  12.307562  4.494397  ...     32.99    24.80       6.37
118043   None   6.317041  5.603633  ...     61.34    71.34      67.57
57035    None   7.481465  7.199317  ...     50.71    53.05      63.74
22919    None   4.052163  9.772495  ...     18.64     5.76       0.88
118091   None   6.356999  5.671823  ...     41.20    48.95      78.62
110240   None   6.324177  5.625228  ...     54.37    56.46      73.18
110248   None   6.299585  5.629651  ...     62.46    59.87      93.04
118079   None   7.061459  6.276448  ...     90.87    70.76     113.47
99111    None   7.402230  3.978691  ...     68.48   108.29      58.37
109220   None   7.384663  3.945290  ...     61.83    93.51      79.40
109228   None   7.378107  3.954845  ...     73.23   108.81      77.41
109446   None   7.378437  3.953661  ...     54.85    79.38      78.25
109454   None   7.370136  3.993421  ...     62.62    97.64      65.75
102718   None   7.382587  3.932735  ...     61.14    89.43      62.45
102688   None   7.389509  3.944217  ...    127.85    96.18      35.00
102938   None   7.383283  3.950495  ...    123.22   105.13      47.90
99043    None   7.350419  3.953661  ...     72.57    99.67      57.58
98997    None   7.403604  3.905106  ...    107.25   123.38      62.05
102716   None   7.349429  3.953799  ...     49.80    68.67      62.48
102722   None   7.377544  3.947011  ...    152.86   156.92      69.40
102702   None   7.340042  3.950384  ...     82.51   119.10      86.10
102936   None   7.429316  3.905791  ...     68.78    98.55      74.13
99107    None   7.354617  3.945820  ...     75.14   104.14      65.11
102698   None   7.392963  3.956662  ...     92.04   110.80      68.67
102930   None   7.371220  3.954707  ...    206.75   174.97      67.28
44315    None   6.451397  3.471201  ...      1.73     1.81       6.36
57391    None   5.537100  6.061280  ...    160.03   108.75      49.24
97063    None   4.806780  7.002953  ...     60.73    59.77      60.76
118095   None   7.139774  6.182620  ...    116.14    86.70     143.91
124471   None   6.517566  6.196515  ...     50.68    53.18      46.72
57343    None   8.990670  7.383702  ...     46.34    50.21      61.29
57211    None  11.979944  8.480097  ...     97.05    80.60      55.16
57321    None   6.403880  5.619492  ...     42.09    48.55      86.98
33565    None   7.444260  3.894734  ...      2.55     3.79       9.47
47447    None   8.483760  4.678557  ...     38.45    42.40      36.11

[37 rows x 43 columns]

Can we extract the PM2.5 values from all the locations in West Africa?

In [88]:
westafr_pm25 = []
loc = []
for i,ii in enumerate(hd.index):
  
  we = Sensor(ii)
  xc = we.parent.get_historical(1,thingspeak_field='primary')
  
  if len(xc) > 5000:
    westafr_pm25.append(xc['PM2.5 (CF=1) ug/m3'].values)
    print([i,ii,len(xc)])
    loc.append(ii)

westafr = pd.DataFrame(westafr_pm25).T
westafr.columns = loc
westafr
#westafr.plot()

      57207   118091  110248  44315   118095
0      95.19   89.42   60.56    2.00   85.41
1      95.93   79.62   62.70    1.84   86.69
2      95.07   76.15   61.66    2.02   88.11
3      95.88   74.27   60.46    1.86   87.79
4      94.57   61.37   60.36    2.00   87.41
...      ...     ...     ...     ...     ...
5034   53.26     NaN     NaN     NaN     NaN
5035   54.73     NaN     NaN     NaN     NaN
5036   53.11     NaN     NaN     NaN     NaN
5037   53.75     NaN     NaN     NaN     NaN
5038   53.68     NaN     NaN     NaN     NaN

[5039 rows x 5 columns]